config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  mount ActionCable.server => '/cable'

  root 'users#new'

  resources :chat_rooms do
    resources :messages
  end

  resources :users
end

app/models/chat_room.rb
class ChatRoom
  include Mongoid::Document
  include Mongoid::Timestamps

  field :title, type: String

  has_many :messages
  has_many :users

  validates_presence_of :title
  validates_uniqueness_of :title

end

app/models/message.rb
class Message
  include Mongoid::Document
  include Mongoid::Timestamps

  field :body, type: String
  belongs_to :user
  belongs_to :chat_room

  index({ starred: 1 })

  validates_presence_of :user
  validates_presence_of :chat_room
  validates :body, presence: true, length: {minimum: 2, maximum: 1000}

  after_create { MessagesRelayJob.perform_now(self) }


  def timestamp
    created_at.strftime('%H:%M:%S %d %B %Y')
  end

end

app/models/user.rb
class User
  include Mongoid::Document
  include Mongoid::Timestamps

  field :name, type: String

  has_many :messages
  has_many :chat_rooms

  validates_presence_of :name
  validates_uniqueness_of :name

  def destroyable
    messages.empty?
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :user_login?

  def user_login?
    if cookies.signed[:user_name].blank?
      redirect_to root_path
    end
  end

end

app/controllers/chat_rooms_controller.rb
class ChatRoomsController < ApplicationController
  before_action :set_chat_room, only: [:edit, :update, :destroy]
  before_action :set_chat_rooms, only: :index

  # GET /chat_rooms
  # GET /chat_rooms.json
  def index
  end

  # GET /chat_rooms/1
  # GET /chat_rooms/1.json
  def show
    @chat_room = ChatRoom.includes(:messages).find_by(id: params[:id])
    @message = Message.new
  end

  # GET /chat_rooms/new
  def new
    @chat_room = ChatRoom.new
  end

  # GET /chat_rooms/1/edit
  def edit
  end

  # POST /chat_rooms
  # POST /chat_rooms.json
  def create
    @chat_room = ChatRoom.new(chat_room_params)

    respond_to do |format|
      if @chat_room.save
        set_chat_rooms
        format.html { redirect_to chat_rooms_path, notice: 'Chat room was successfully created.' }
        format.js { render :create }
        format.json { render :show, status: :created, location: @chat_room }
      else
        format.js { render :new }
        format.json { render json: @chat_room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chat_rooms/1
  # PATCH/PUT /chat_rooms/1.json
  def update
    respond_to do |format|
      if @chat_room.update(chat_room_params)
        format.html { redirect_to chat_rooms_path, notice: 'Chat room was successfully updated.' }
        format.js { render :update }
        format.json { render :index, status: :ok, location: @chat_room }
      else
        format.html { render :edit }
        format.js { render :edit }
        format.json { render json: @chat_room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chat_rooms/1
  # DELETE /chat_rooms/1.json
  def destroy
    respond_to do |format|
      if @chat_room.messages.empty? and @chat_room.destroy
        format.html { redirect_to chat_rooms_url, notice: 'Chat room was successfully destroyed.' }
        format.json { head :no_content }
      else
        format.html { redirect_to chat_rooms_url, notice: 'Chat room cannot be destroyed.' }
        format.json { render json: @chat_room.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_chat_room
    @chat_room = ChatRoom.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def chat_room_params
    params.require(:chat_room).permit(:title)
  end

  def set_chat_rooms
    @chat_rooms = ChatRoom.all
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_chat_room, only: :create
  before_action :set_current_user, only: :create


  # POST /messages
  # POST /messages.json
  def create
    @message = Message.new(message_params)
    respond_to do |format|
      if @message.save
        format.html { redirect_to @chat_room, notice: "Message was successfully created." }
        format.js
        format.json { render :show, status: :created, location: @message }
      else
        format.html { render 'chat_rooms/show' }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  # Never trust parameters from the scary internet, only allow the white list through.
  def message_params
    params.require(:message).permit(:body).tap do |whitelisted|
      whitelisted[:chat_room_id] = @chat_room.id
      whitelisted[:user_id] = @current_user.id
    end
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_chat_room
    @chat_room = ChatRoom.find(params[:chat_room_id])
  end

  def set_current_user
    @current_user = User.find_by( name: cookies.signed[:user_name])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :user_login?, only: [:create, :new]

  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :find_or_initialize, only: :create

  # GET /users
  # GET /users.json
  def index
    @users = User.all
    respond_to do |format|
      format.html
      format.json { render :json => @users.to_json( methods: [:destroyable]) }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    respond_to do |format|
      if @user.save
        set_current_user
        format.html { redirect_to chat_rooms_path(), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { redirect_to root_path }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    respond_to do |format|
      if @user.destroyable and @user.destroy
        format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
        format.json { render :json => User.all }
      else
        format.html { redirect_to users_url, notice: 'User cannot be destroyed.' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:name)
  end

  def find_or_initialize
    @user = User.find_or_initialize_by(user_params)
  end

  def set_current_user
    cookies.signed[:user_name] = @user.name
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chat_rooms_helper.rb
module ChatRoomsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/chat_rooms/_form.html.slim
#chat_room_form= form_for chat_room, remote: true do |form|
  - if chat_room.errors.any?
    #error_explanation
      h2
        = pluralize(chat_room.errors.count, "error")
        | prohibited this chat_room from being saved:
      ul
        - chat_room.errors.full_messages.each do |message|
          li= message
  .field
    = form.label :title
    = form.text_field :title, id: :chat_room_title, class: 'form-control', 'v-model':'title'
  .actions.form-space
    = form.submit "Send", class: 'btn btn-primary btn-lg', 'v-bind:disabled': '!isFormValid()'


javascript:
  chat_room_vue_observer();

app/views/chat_rooms/_row.html.slim
td= chat_room.title
td= link_to 'Show', chat_room
td= link_to 'Edit', edit_chat_room_path(chat_room), remote: true

- if chat_room.messages.empty?
  td= link_to 'Destroy', chat_room, method: :delete, data: { confirm: 'Are you sure?' }

app/views/chat_rooms/_table.html.slim
table.table
  thead
    tr
      th scope="col"  Title
      th colspan="3"
  tbody
    - chat_rooms.try(:each) do |chat_room|
      tr id="chat_room_#{chat_room.id}"
        = render partial: 'row', locals: { chat_room: chat_room }

app/views/chat_rooms/create.js.erb
$("#chat_rooms").html("<%= j render partial: "chat_rooms/table", locals: { chat_rooms: @chat_rooms } %>");
$('#modal').modal('hide');

app/views/chat_rooms/edit.html.slim
h1 Editing Chat Room

= render 'form', chat_room: @chat_room

.form-space
= link_to 'Show', @chat_room
.form-space
= link_to 'Back', chat_rooms_path
 

app/views/chat_rooms/edit.js.erb
<%= render  partial: 'layouts/render_modal', locals: { partial: 'form', chat_room: @chat_room } %>

app/views/chat_rooms/index.html.slim
.container
  h1 Chat rooms

  #chat_rooms = render partial: 'table', locals: {chat_rooms: @chat_rooms }

  .inline.form-space
    = link_to 'New chat room', new_chat_room_path, class: 'btn btn-primary', remote: true
    = link_to 'Users', users_path, class: 'btn btn-primary marginleft10'

app/views/chat_rooms/new.html.slim
h1 New Chat Room
= render 'form', chat_room: @chat_room
.form-space
= link_to 'Back', chat_rooms_path
 

app/views/chat_rooms/new.js.erb
<%= render  partial: 'layouts/render_modal', locals: { partial: 'form', chat_room: @chat_room } %>

app/views/chat_rooms/show.html.slim
section data-channel="chat_rooms" data-chat-room-id="#{@chat_room.id}"
p
.container
  strong Chat Room:
  = @chat_room.title
.form-space
.container id=("chat_room_messages_#{ @chat_room.id }")
  = render @chat_room.messages
.container
  = render partial: 'messages/form', locals: { chat_room: @chat_room, message: @message }

  .inline.form-space
    = link_to 'Edit', edit_chat_room_path(@chat_room), class: 'btn btn-primary'
    = link_to 'Back', chat_rooms_path, class: 'btn btn-primary marginleft10'

app/views/chat_rooms/update.js.erb
$('#modal').modal('hide');
$("#chat_room_<%= @chat_room.id %>").html("<%= j render 'row', { chat_room: @chat_room }%>");

app/views/layouts/_modal.html.slim
#modal.modal.fade aria-hidden="true" aria-labelledby="exampleModalLabel" role="dialog" tabindex="-1" 
  .modal-dialog role="document" 
    .modal-content
      .modal-header
        h5#exampleModalLabel.modal-title Chat room
        button.close aria-label="Close" data-dismiss="modal" type="button" 
          span aria-hidden="true"  ×
      .modal-body
        = render partial: partial, locals: local_assigns

app/views/layouts/_render_modal.js.erb
$("#modal_div").html("<%= j render partial: 'layouts/modal', locals: local_assigns %>");
$('#modal').modal('show');

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title Chat
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    p.notice= notice
    p.alert= alert
    #modal_div
    #app= yield

app/views/messages/_form.html.slim
.form-space
#message_form= form_for message, url: chat_room_messages_path(chat_room), remote: true do |f|
  .form-group
    = f.text_area :body,{ class: 'form-control', placeholder: 'write a message', 'v-model': 'body' }
    small.text-muted From 2 to 1000 characters
  .form-space
  = f.submit "Post", class: 'btn btn-primary btn-lg', 'v-bind:disabled': '!isFormValid()',  'v-on:click': 'resetForm($event)'

javascript:
    message_vue_observer();

app/views/messages/_message.html.slim
.card
  .card-block
    .row
      .col-md-1
        = message.user.name
      .col-md-11
        p.card-text
          span.text-muted
            = message.user.name
            | at #{message.timestamp} says
          br
          = message.body

app/views/users/_form.html.slim
- btn_text ||= params[:action]
#user_form= form_with(model: user, local: true) do |f|
  - if user.errors.any?
    #error_explanation
      h2 = pluralize(user.errors.count, "error")
      | prohibited this user from being saved:
      ul
      - user.errors.full_messages.each do |message|
      li= message

  .field.form-space
    = f.text_field :name, id: :user_name, class: 'form-control', placeholder: :name, 'v-model': 'name'
  .actions.form-space
    = f.submit btn_text, class: 'btn btn-primary btn-lg', 'v-bind:disabled': '!isFormValid()'

javascript:
  user_vue_observer();

app/views/users/edit.html.slim
.container
  h1 Editing User
  = render 'form', user: @user, btn_txt: 'Edit'

  .form-space.inline
    = link_to 'Show', @user, class: 'btn btn-primary'
    = link_to 'Users', users_path, class: 'btn btn-primary marginleft10'

app/views/users/index.html.slim
#users.container
  h1 Users
  table.table
    thead
      tr
        th scope="col"  Username
        th colspan="3"
    tbody
      tr v-for=("user in users") v-bind:id="user._id.$oid"
        td
          | {{ user.name }}
        td
          a v-bind:href="showLink(user)"
            | Show
        td
          a v-bind:href="editLink(user)"
            | Edit
        td
          a v-if="user.destroyable" v-bind:href="deleteLink(user)" data-confirm="Are you sure?" rel="nofollow" data-method="delete"
            | Delete

  .inline.form-space
    = link_to 'New user', root_path, class: 'btn btn-primary'
    = link_to 'Chat rooms', chat_rooms_path, class: 'btn btn-primary marginleft10'

script type="application/javascript"
  | users_table_vue_observer();

app/views/users/new.html.slim
.container
  h1 New User
  = render 'form', user: @user, btn_text: 'Login'

app/views/users/show.html.slim
.container

  h1 User
  p
    strong Name:
    = @user.name

  .inline.form-space
    = link_to 'Edit', edit_user_path(@user), class: 'btn btn-primary'
    = link_to 'Users', users_path, class: 'btn btn-primary marginleft10'